version: '2'
services:
  mikutter:
    image: mikutter:mikutter-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: mikutter
    volumes:
      - "./conf.d/config:/home/mikutter/.mikutter:Z"
    command: "/usr/local/bin/ruby /home/mikutter/mikutter/mikutter.rb --plugin=twitter_api_keys,ahiru_yakuna --debug"
    stdin_open: true
    tty: true
    environment:
      - "TZ=Asia/Tokyo"

